# -*- coding: utf-8 -*-
"""Bernoulli-dist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfqL51VYfKBGjLF68v4xwGcUIsp43UoT
"""

import numpy as np
from scipy.stats import bernoulli
import matplotlib.pyplot as plt

p = 0.5
mean, var, s, k = bernoulli.stats(p, moments='mvsk')

fig, ax = plt.subplots(1, 1)
x = np.arange(bernoulli.ppf(0.01, p), bernoulli.ppf(0.99, p))
ax.plot(x, bernoulli.pmf(x, p), 'bo', ms=8, label='bernoulli pmf')
ax.vlines(x, 0, bernoulli.pmf(x, p), colors='b', lw=5, alpha=0.5)

