# -*- coding: utf-8 -*-
"""normal-dist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfqL51VYfKBGjLF68v4xwGcUIsp43UoT
"""

from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

x = random.normal(5,80,size=1000)

sns.distplot(x)

plt.show()

