# -*- coding: utf-8 -*-
"""poisson-dist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfqL51VYfKBGjLF68v4xwGcUIsp43UoT
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

x = np.random.poisson(lam=2, size=10)

sns.distplot(random.poisson(lam=2, size=1000), kde=False)
plt.show()

