# -*- coding: utf-8 -*-
"""T-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1LCfRxxXKe277a9UI47N_CnnGljerFy
"""

import numpy as np
from scipy import stats
import random
np.random.choice

populatuin_data = np.random.randint(0,100,50)
sample_data = np.random.choice(populatuin_data,15,replace=False)
print(populatuin_data,'\n',sample_data)

sample_mean = sample_data.mean()
mu = populatuin_data.mean()
print(sample_mean,'\n',mu)

t_stat, p_value = stats.ttest_1samp(sample_data, mu)
print("T statistic:", t_stat)
print("P-value:", p_value)

# Acceptence criteria
alpha = 0.05

if p_value < alpha:
    print("reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

def t_test(sample,mu,alpha):
  sample_mean = sample.mean()
  stdev = np.std(sample)
  T =  (sample_mean - mu) / (stdev/len(sample_data*0.5))
  if T < alpha:
    print("reject the null hypothesis")
  else:
    print("Fail to reject the null hypothesis")

t_test(sample_data,mu,alpha)

